seed: 42
exp_name: cnn

device:
  device_type: gpu
  worker: cuda:0
  gpu_num_workers: 32

data:
  dataset: generali
  classes:
    0: non_crash
    1: crash
  fold_dir: ./data/processed/
  data_dir: ./data/data_raw/
  interim_dir: ./data/interim/
  modes:
    acc:
      timestamp: 2490
      channel: 3
    pos:
      timestamp: 41
      channel: 1

model:
  model_name: cnn_1d_001
  model_dir: ./models/

trainer:
  thr_cnn: 0.5061745
  thr_lstm: 0.23062487
      
reports:
  reports_dir: "./reports/"