seed: 42

device:
  device_type: gpu
  worker: cuda:0
  gpu_num_workers: 32

data:
  data_source: E:/Lorenzo Tronchin/DATA_STAGE-REPOSITORY/XAI_Generali/Generali_Data_Models/data3
  data_dest: ./data/data_raw/holdout
  data_fold: ./data/processed/holdout
  modes:
    acc:
    pos: