seed: 42

device:
  device_type: gpu
  worker: cuda:0
  gpu_num_workers: 32

data:
  dataset: generali
  classes:
    - crash
    - non_crash
  fold_dir: ./data/processed/holdout
  data_dir: ./data/data_raw/holdout
  interim_dir: ./data/interim/holdout
  modes:
    acc:
      timestamp: 2490
      channel: 3
    pos:
      timestamp: 41
      channel: 1

model:
  model_name: cnn_1d_001
  model_dir: ./models/holdout

xai:
  step_to_explain: valid
  n_samples_to_explain: 1000
  list_samples_to_explain: ['C_89', 'C_90']
  class_to_explain: 2 # ground_truth (0: crash, 1: non_crash, 2: ground_truth, 3: cnn_prediction)
  methods:
    - lime
    - gradcam
    - ig
  lime:
    num_features: 5  # massimo numero di feature da selezionare (parametri del regressore lineare) per ottenere
    # la spiegazione
    num_samples: 1000
    top_labels: 2
    hide_color: 0  # -1 #0 #None
    random_state: 42  # Con il random state pari a 42 si forza il generatore a produrre sempre gli stessi numeri
    feature_selection: 'auto'  # feature_selection: metodo di feature selection
  gradcam:

  ig:
    baseline_crash: 0     # ground_truth (0: constant value, 1: uniform value, 2: signal that activates most on the opposite class)
    baseline_non_crash: 2
    m_steps: 500
    const_value_acc: 0
    const_value_vel: 0.1


trainer:
  thr_cnn: 0.5061745
  thr_lstm: 0.23062487
      
reports:
  reports_dir: "./reports/"
  snap: True